// AUTH
export const SET_IS_AUTHORIZED = 'SET_IS_AUTHORIZED';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';

// USER
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const EDIT_USER = 'EDIT_USER';
export const SET_USER_FOR_EDIT = 'SET_USER_FOR_EDIT';
export const SET_CHANGE_PASS_POPUP = 'SET_CHANGE_PASS_POPUP';
export const SET_PASS = 'SET_PASS';
export const CLEAR_CHANGE_PASS_FORM = 'CLEAR_CHANGE_PASS_FORM';
export const SET_PASS_FORM_ERRORS = 'SET_PASS_FORM_ERRORS';
export const SET_EDITABLE_USER_DATA = 'SET_EDITABLE_USER_DATA';
export const EDIT_TOUR_OPERATOR_FORM_ERRORS = 'EDIT_TOUR_OPERATOR_FORM_ERRORS';
export const EDIT_TOUR_OPERATOR_FORM_FIELD = 'EDIT_TOUR_OPERATOR_FORM_FIELD';
export const EDIT_TOUR_OPERATOR_FORM_MESSAGE_STARTED =
  'EDIT_TOUR_OPERATOR_FORM_MESSAGE_STARTED';
export const EDIT_TOUR_OPERATOR_FORM_MESSAGE_FINISHED =
  'EDIT_TOUR_OPERATOR_FORM_MESSAGE_FINISHED';
export const CLEAR_TOUR_OPERATOR_FORM_EDIT_MESSAGE_STATUS =
  'CLEAR_TOUR_OPERATOR_FORM_EDIT_MESSAGE_STATUS';
export const EDIT_ACCOUNT_FORM_ERRORS = 'EDIT_ACCOUNT_FORM_ERRORS';
export const EDIT_ACCOUNT_FORM_FIELD = 'EDIT_ACCOUNT_FORM_FIELD';
export const CLEAR_ACCOUNT_FORM = 'CLEAR_ACCOUNT_FORM';
export const EDIT_ACCOUNT_MESSAGE_STARTED = 'EDIT_ACCOUNT_MESSAGE_STARTED';
export const EDIT_ACCOUNT_MESSAGE_FINISHED = 'EDIT_ACCOUNT_MESSAGE_FINISHED';
export const CLEAR_ACCOUNT_MESSAGE_STATUS = 'CLEAR_ACCOUNT_MESSAGE_STATUS';
export const SET_USER_CURRENT_LOCATION = 'SET_USER_CURRENT_LOCATION';
export const SET_USER_ACTIVE = 'SET_USER_ACTIVE';

// COMPANY
export const SET_COMPANY_DATA = 'SET_COMPANY_DATA';
export const SET_COMPANY_FOR_EDIT = 'SET_COMPANY_FOR_EDIT';
export const EDIT_COMPANY = 'EDIT_COMPANY';
export const SWITCH_RANGE_PICKER = 'SWITCH_RANGE_PICKER';

// PROPERTY
export const SET_PROPERTY_DATA = 'SET_PROPERTY_DATA';

// ROUTES
export const SELECT_SINGLE_ROUTE = 'SELECT_SINGLE_ROUTE';
export const SELECT_ROUTES = 'SELECT_ROUTES';
export const SET_ROUTE_TITLE = 'SET_ROUTE_TITLE';
export const SET_ROUTES = 'SET_ROUTES';
export const SET_EDIT_ROUTE_ID = 'SET_EDIT_ROUTE_ID';
export const SET_WAYPOINTS = 'SET_WAYPOINTS';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORY_COLOR = 'SET_CATEGORY_COLOR';
export const SET_STATUS = 'SET_STATUS';

// POSTS
export const ADD_POST = 'ADD_POST';
export const SET_POSTS = 'SET_POSTS';
export const SET_POST_TYPES = 'SET_POST_TYPES';
export const SET_SELECTED_POST_TYPE = 'SET_SELECTED_POST_TYPE';
export const SET_PHOTO_OPTION = 'SET_PHOTO_OPTION';
export const SET_WORK_OPTION = 'SET_WORK_OPTION';
export const SET_DOCUMENT_OPTION = 'SET_DOCUMENT_OPTION';
export const SET_PERMIT_DOCUMENT_OPTION = 'SET_PERMIT_DOCUMENT_OPTION';
export const SET_HISTORICAL_DOCUMENT_OPTION = 'SET_HISTORICAL_DOCUMENT_OPTION';
export const SET_HIST_DOCUMENT_COMPANY = 'SET_HIST_DOCUMENT_COMPANY';
export const SET_PERMIT_DOCUMENT_COMPANY = 'SET_PERMIT_DOCUMENT_COMPANY';
export const SET_DOCUMENT_ISSUED_BY = 'SET_DOCUMENT_ISSUED_BY';
export const SET_HIST_DOCUMENT_AUTHOR = 'SET_HIST_DOCUMENT_AUTHOR';
export const SET_PERMIT_DOCUMENT_AUTHOR = 'SET_PERMIT_DOCUMENT_AUTHOR';
export const SET_DOCUMENT_PUBLISHED_BY = 'SET_DOCUMENT_PUBLISHED_BY';
export const SET_DOCUMENT_YEAR = 'SET_DOCUMENT_YEAR';
export const SET_SELECTED_DOCUMENT_TYPE = 'SET_SELECTED_DOCUMENT_TYPE';
export const SET_SELECTED_WORK_TYPE = 'SET_SELECTED_WORK_TYPE';
export const SET_EVENT_DATE = 'SET_EVENT_DATE';
export const SET_COMPANY_WORK = 'SET_COMPANY_WORK';

// SEARCH
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

// MODAL DIALOG
export const SET_SIGN_IN_DIALOG = 'SET_SIGN_IN_DIALOG';
export const SET_SIGN_UP_DIALOG = 'SET_SIGN_UP_DIALOG';

// SIGN UP FORM
export const SET_SIGN_UP_FORM_ERRORS = 'SET_SIGN_UP_FORM_ERRORS';
export const SET_SIGN_UP_FORM_FIELD = 'SET_SIGN_UP_FORM_FIELD';
export const CLEAR_SIGN_UP_FORM = 'CLEAR_SIGN_UP_FORM';

export const ADD_SIGN_UP_MESSAGE_STARTED = 'ADD_SIGN_UP_MESSAGE_STARTED';
export const ADD_SIGN_UP_MESSAGE_FINISHED = 'ADD_SIGN_UP_MESSAGE_FINISHED';
export const CLEAR_SIGN_UP_MESSAGE_STATUS = 'CLEAR_SIGN_UP_MESSAGE_STATUS';

// SIGN IN FORM
export const SET_SIGN_IN_FORM_ERRORS = 'SET_SIGN_IN_FORM_ERRORS';
export const SET_SIGN_IN_FORM_FIELD = 'SET_SIGN_IN_FORM_FIELD';
export const CLEAR_SIGN_IN_FORM = 'CLEAR_SIGN_IN_FORM';

export const ADD_SIGN_IN_MESSAGE_STARTED = 'ADD_SIGN_IN_MESSAGE_STARTED';
export const ADD_SIGN_IN_MESSAGE_FINISHED = 'ADD_SIGN_IN_MESSAGE_FINISHED';
export const CLEAR_SIGN_IN_MESSAGE_STATUS = 'CLEAR_SIGN_IN_MESSAGE_STATUS';

// MERCHANT FORM
export const EDIT_MERCHANT_FORM_ERRORS = 'EDIT_MERCHANT_FORM_ERRORS';
export const EDIT_MERCHANT_FORM_FIELD = 'EDIT_MERCHANT_FORM_FIELD';
export const CLEAR_MERCHANT_EDIT_FORM = 'CLEAR_MERCHANT_EDIT_FORM';
export const EDIT_MERCHANT_FORM_MESSAGE_STARTED =
  'EDIT_MERCHANT_FORM_MESSAGE_STARTED';
export const EDIT_MERCHANT_FORM_MESSAGE_FINISHED =
  'EDIT_MERCHANT_FORM_MESSAGE_FINISHED';
export const CLEAR_MERCHANT_EDIT_FORM_MESSAGE_STATUS =
  'CLEAR_MERCHANT_EDIT_FORM_MESSAGE_STATUS';
export const SET_EDITABLE_MERCHANT_DATA = 'SET_EDITABLE_MERCHANT_DATA';
export const SET_ACCOUNT_DATA = 'SET_ACCOUNT_DATA';
export const SET_TOUR_OPERATOR_FORM = 'SET_TOUR_OPERATOR_FORM';

// FILE
export const SET_FILES = 'SET_FILES';

// LOADER
export const SET_LOADER = 'SET_LOADER';

// BROWSER
export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE';
export const SET_WINDOW_ORIENTATION = 'SET_WINDOW_ORIENTATION';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';
export const SET_ONLINE = 'SET_ONLINE';
export const SET_SCROLL = 'SET_SCROLL';

// SUGGESTIONS
export const SET_SUGGESTIONS = 'SET_SUGGESTIONS';
export const SET_SELECTED_WORK_COMPANY_SUGGESTION =
  'SET_SELECTED_WORK_COMPANY_SUGGESTION';
export const SET_SELECTED_HIST_DOC_COMPANY_SUGGESTION =
  'SET_SELECTED_HIST_DOC_COMPANY_SUGGESTION';
export const SET_SELECTED_PER_DOC_COMPANY_SUGGESTION =
  'SET_SELECTED_PER_DOC_COMPANY_SUGGESTION';
export const SET_SELECTED_PROPERTY_SUGGESTION =
  'SET_SELECTED_PROPERTY_SUGGESTION';
export const SET_SELECTED_SIGNUP_SUGGESTION = 'SET_SELECTED_SIGNUP_SUGGESTION';
// MAP
export const SET_TOTAL_ROUTE_STOP = 'SET_TOTAL_ROUTE_STOP';
export const SET_TOTAL_DISTANCE = 'SET_TOTAL_DISTANCE';
export const SET_PROPERTIES = 'SET_PROPERTIES';
export const SET_ALL_PROPERTIES = 'SET_ALL_PROPERTIES';
export const SET_TRAVEL_MODE = 'SET_TRAVEL_MODE';
export const SET_ROUTE_STOP_MARKER = 'SET_ROUTE_STOP_MARKER';
export const SET_ROUTE_STOP_PARAMS = 'SET_ROUTE_STOP_PARAMS';
export const SET_INFO_WINDOW = 'SET_INFO_WINDOW';
export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const SET_USER_POSTS_PROPERTIES = 'SET_USER_POSTS_PROPERTIES';
export const SET_POINT = 'SET_POINT';
export const RESET_MAP_DATA = 'RESET_MAP_DATA';
export const DIS_RERENDER_MAP = 'DIS_RERENDER_MAP';
export const SET_MAP_ROUTES = 'SET_MAP_ROUTES';

// REGISTER TOUR OPERATOR FORM
export const SET_TOUR_OPERATOR_FORM_ERRORS = 'SET_TOUR_OPERATOR_FORM_ERRORS';
export const SET_TOUR_OPERATOR_FORM_FIELD = 'SET_TOUR_OPERATOR_FORM_FIELD';
export const CLEAR_TOUR_OPERATOR_FORM = 'CLEAR_TOUR_OPERATOR_FORM';

export const ADD_TOUR_OPERATOR_FORM_MESSAGE_STARTED =
  'ADD_TOUR_OPERATOR_FORM_MESSAGE_STARTED';
export const ADD_TOUR_OPERATOR_FORM_MESSAGE_FINISHED =
  'ADD_TOUR_OPERATOR_FORM_MESSAGE_FINISHED';
export const CLEAR_TOUR_OPERATOR_FORM_MESSAGE_STATUS =
  'CLEAR_TOUR_OPERATOR_FORM_MESSAGE_STATUS';

// TOURS
export const SET_MULTIMEDIA_FILE = 'SET_MULTIMEDIA_FILE';
export const SET_AUDIO_FILE = 'SET_AUDIO_FILE';
export const SET_PHOTOS = 'SET_PHOTOS';
export const SET_TOUR_EDITABLE = 'SET_TOUR_EDITABLE';
export const SET_TOUR_PHOTO = 'SET_TOUR_PHOTO';
export const SET_TOUR_IMAGE_WIDTH = 'SET_TOUR_IMAGE_WIDTH';

// PAYMENT METHODS
export const SET_PAYMENT_METHODS = 'SET_PAYMENT_METHODS';
export const SET_EDIT_CARD = 'SET_EDIT_CARD';

//FILTERS
export const SET_FILTERS = 'SET_FILTERS';

//FULLSCREEN
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
